name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: egor-tensin/setup-gcc@v1
      with:
        version: latest

    - run: |
        sudo apt install -y make

    - name: Build
      run: make -j
